### ISSUE TITLE
Tasks System Tracking Issue

### ISSUE THREAD

**Issue by WardenDrew** [devmatics/clockwork-issues#29]
Tracking issue for all Tasks System related issues

API:
- [ ] https://github.com/devmatics/clockwork-api/issues/3
- [ ] https://github.com/devmatics/clockwork-api/issues/9
- [ ] https://github.com/devmatics/clockwork-api/issues/27

App:
- [ ] https://github.com/devmatics/clockwork-app/issues/31

Portal:
- [ ] https://github.com/devmatics/clockwork-portal/issues/49
- [ ] https://github.com/devmatics/clockwork-portal/issues/3

Other:

**Comment by ARegalbuto** [comment]
@alexdwhite @WardenDrew How are we doing with these tasks.  Will they be resolved with API v2?

**Comment by alexdwhite** [comment]
Some will, some sub issues are part of later releases.
